sudo: false
language: python
env:
  matrix:
  - TESTENV=py26
  - TESTENV=py27
  - TESTENV=py34
  - TESTENV=coveralls
install:
- pip install tox
script: tox -e $TESTENV
notifications:
  email:
  - opensource-tests@paylogic.com
  slack:
    secure: CXfMTg1lZzKuvJZ3ZUkTriWaM9YjujGutPFFmGN5zJGzkgewMD8DgrpMm32MqaVYHdfCn4sM3r1GAqtBJqU9PcStoJbNAMQsuR7QEcOR0Uhou/tBsRTVAfaeLjOlBG1MVVhhSWr89SvGQetN+Fv4kKECaBfkAdnD0hFmg/XgyxE=
